### ISSUE TITLE
Clearing Tech Debt / Code Refactoring

### ISSUE THREAD

**Issue by cliffchew84** [cliffchew84/SG-Lib-Books#158]
Description:
Currently, the codebase is in quite a mess, as the sole developer @cliffchew84 has been focused on just trying to hack out a somehow workable tool for himself. However, he understands that his code is in dire need of much refactoring and repayment of tech debt. 

Proposed solutions / help needed:
- [x] General clean up current code base to remove legacy backend code
- [x] Refactor current FastAPI main.py file into more maintainable 
- [x] Removal of old accounts that have not logged in for more than X months
- [ ] Adding of unit tests ( what types of units tests can be further discussion )

**Comment by kiritowu** [comment]
Other potential improvements includes:
- [ ] More modern dependencies management with [uv](https://docs.astral.sh/uv/) or [poetry](https://python-poetry.org/)
- [ ] Implement Supabase-CLI as local staging environment for postgre database and data migration requirement without touching production environment.
- [ ] Documentation for getting started as developer.

**Comment by kiritowu** [comment]
@cliffchew84 As discussed in our previous meetup, happy to share that all of the refactoring work has been completed in `staging` and ready to be merged to `main`.

However, since in #182, `uv` is added as dependency management solution, help is required to update the deploy instruction in `on-render`'s configurations to the following:
- Build Command: 
    ```bash
    curl -LsSf https://astral.sh/uv/install.sh | sh
    ```
- Start Command:
    ```bash
    uv run -- uvicorn src.main:app --host 0.0.0.0 --port 10000
    ```

Since UV is a relatively new tool, documentation on deploying for on-render could not be found so some trial-and-error with the configuration might be required.

**Comment by kiritowu** [comment]
Also since work on adding proper supabase authentication and unit test requires the usage of Javascript Framework as discussed, may I request the 2 leftover tasks to be created in seperate issue? Then this issue can be closed.

**Comment by cliffchew84** [comment]
I tried shifting to uv, but couldn't get it to work so far. Here are the steps that I have taken:
1. [ Success ] Shifted to Python 3.9.10 using the docs here - https://docs.render.com/python-version, as uv needs to use at least Python 3.8, and my original Python setup on Render was Python 3.7. I tried to shift to Python 3.10, but there seems to be some config issues with one of my legacy packages. Once I align my package dependencies with yours, I can consider to shift to Python 3.10>=. 
2. [ Success ] On **Build Command**, I managed to do this `curl -LsSf https://astral.sh/uv/install.sh | sh && export PATH=$PATH:$HOME/.local/bin && uv pip install -r requirements.txt`. My idea was to at least test the installation of uv, while maintaining my current requirements.txt set up for now. Definitely should shift to pyproject.toml set up once I update my packages from you. Logs show that uv and the packages got installed properly, and the build was successful ( and blazingly fast )
3. [ Failed ] On **Start Command**, I tried these two commands `uv run -- uvicorn main:app --host 0.0.0.0 --port 10000` and `export PATH=$PATH:$HOME/.local/bin && uv run -- uvicorn main:app --host 0.0.0.0 --port 10000`, and both commands say `uv command not found`

We can look into debugging this together soon :D

**Comment by kiritowu** [comment]
If the error is `uv not found`, high chance is because the location where `uv` is installed are not carried over to the run layer.

If that's the case, there are two options:
1. Install `uv` binary in some local path that we know for sure will exist in the run layer. (E.g. `./`)
2. Scourge from onrender documentation on exact location to install for custom binary dependency.

Need to test out more over the weekend to figure this out.

**Comment by kiritowu** [comment]
@cliffchew84 I managed to test with a dummy FastAPI repo, the following configuration command works :smiley: 

- Build Command: 
    ```bash
    pip install uv && uv sync --frozen
    ```
- Start Command:
    ```bash
    uv run --no-sync -- uvicorn src.main:app --host 0.0.0.0 --port 10000
    ```
